custom_hostname: PE1
custom_router_bgp:
  as: 65001
  neighbors:
    - ip_address: 192.51.81.1
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.51.82.1
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6

custom_eos_cli: |-   
  interface Ethernet4
    description REGION1
    no switchport
    ip address 192.51.81.2/24 
  !
  interface Ethernet5
    description REGION1
    no switchport
    ip address 192.52.81.2/24
  !
  router bgp 65001
   redistribute connected
  !
  